name: WeatherFucker
main: jp.kaiz.weatherfucker.WeatherFuckerCore
version: 1.1.0-SNAPSHOT
author: Twitter@Kaiz_JP
website: https://github.com/Kai-Z-JP/WeatherFucker
commands:
  weatherfucker:
    usage: /<command> <disable|enable>
    aliases: [wf]
